//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int CarID { get; set; }
        public string CarNumber { get; set; }
        public int ManufactorID { get; set; }
        public int ModelID { get; set; }
        public int DesignID { get; set; }
        public int GearID { get; set; }
        public double Kilometrage { get; set; }
        public int Year { get; set; }
        public bool FunctionalForRent { get; set; }
        public decimal RentDayPrice { get; set; }
        public decimal LateDayRentPrice { get; set; }
        public string Picture { get; set; }
        public int BranchID { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Design Design { get; set; }
        public virtual Gear Gear { get; set; }
        public virtual Manufactor Manufactor { get; set; }
        public virtual Model Model { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
