//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public System.DateTime OrderStartDate { get; set; }
        public System.DateTime OrderEndDate { get; set; }
        public Nullable<System.DateTime> OrderActualEndDate { get; set; }
        public int OrderedCarID { get; set; }
        public int OrderingUserID { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual User User { get; set; }
    }
}
